
site_name: Student Management System User and Developers Documentation
site_url: https://bigachievers123.github.io/project_MK
nav:
    - Home: index.md
theme:
  name: material

  # Define theme features
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  # Language setting
  language: en

  # Color palette for light and dark modes
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple

    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime



     